# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48495bfa4c639b7ecfb4fe130aa6b0ade50185c50ec38ad4a1b5ffa45c379f1f8fc72b9d83376aa165276cafc826a8a8b894085f8fdf75e7b2f6804c3d5446f7

test:
  secret_key_base: ef8a6958561a0e3806a08c1ff8d45571c72e3d25e48d2e7cc3ac0c8fc0474c4f10c4d3cbc66dae89f86d038f8c3e9fe9ca95b81bfc8c39695682b1a7a3747bc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
